export interface Proker {
  id: string;
  title: string;
  date: string;
  type: string;
  platform: string;
  link?: string;
}

export const dataProker: Proker[] = [
  {
    id: "1",
    title: "Sertijab Komunitas",
    date: "December 8, 2024",
    type: "Agenda Komunitas",
    platform: "Offline",
  },
  {
    id: "2",
    title: "Penerimaan Anggota Baru",
    date: "December 8, 2024 → December 13, 2024",
    type: "Penerimaan Anggota Baru",
    platform: "Online",
  },
  {
    id: "3",
    title: "Rapat Umum",
    date: "December 10, 2024",
    type: "Rapat",
    platform: "Online",
  },
  {
    id: "4",
    title: "Sharing Session #1",
    date: "December 12, 2024",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "5",
    title: "Orientasi Anggota Baru",
    date: "December 14, 2024 → December 20, 2024",
    type: "Orientasi Anggota Baru",
    platform: "Online",
  },
  {
    id: "6",
    title: "Mimbar Mahasiswa & Rapat Umum #1",
    date: "December 15, 2024",
    type: "Mimbar Mahasiswa",
    platform: "Offline",
  },
  {
    id: "7",
    title: "Sharing Session #2",
    date: "December 17, 2024",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "8",
    title: "Sharing Session #3",
    date: "December 22, 2024",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "9",
    title: "Sharing Session #4",
    date: "January 7, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "10",
    title: "Sharing Session #5",
    date: "January 14, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "11",
    title: "Mimbar Mahasiswa, Rapat Umum",
    date: "January 19, 2025",
    type: "Mimbar Mahasiswa",
    platform: "Offline",
  },
  {
    id: "12",
    title: "Sharing Session #6",
    date: "January 21, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "13",
    title: "Sharing Session #7",
    date: "January 27, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "14",
    title: "Sharing Session #8",
    date: "February 6, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "15",
    title: "Ruang Aspirasi Mahasiswa, Rapat",
    date: "February 16, 2025",
    type: "Mimbar Mahasiswa",
    platform: "Online",
  },
  {
    id: "16",
    title: "Workshop/Diklat",
    date: "February 23, 2025",
    type: "Workshop",
    platform: "Offline",
  },
  {
    id: "17",
    title: "Sharing Session #9",
    date: "March 5, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "18",
    title: "Penerimaan Anggota Baru",
    date: "March 5, 2025",
    type: "Penerimaan Anggota Baru",
    platform: "Online",
  },
  {
    id: "19",
    title: "Orientasi Anggota Baru",
    date: "March 11, 2025 → March 17, 2025",
    type: "Orientasi Anggota Baru",
    platform: "Online",
  },
  {
    id: "20",
    title: "Mimbar Mahasiswa, Bukber",
    date: "March 16, 2025",
    type: "Mimbar Mahasiswa",
    platform: "Offline",
  },
  {
    id: "21",
    title: "Halal Bi Halal",
    date: "April 6, 2025",
    type: "Meetup",
    platform: "Offline",
  },
  {
    id: "22",
    title: "Sharing Session #10",
    date: "April 17, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "23",
    title: "Mimbar Mahasiswa, Rapat Umum",
    date: "April 20, 2025",
    type: "Mimbar Mahasiswa",
    platform: "Offline",
  },
  {
    id: "24",
    title: "Sharing Session #11",
    date: "April 25, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "25",
    title: "Sharing Session #12",
    date: "May 1, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "26",
    title: "Sharing Session #13",
    date: "May 13, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "27",
    title: "Ruang Aspirasi Mahasiswa, Rapat Umum",
    date: "May 18, 2025",
    type: "Mimbar Mahasiswa",
    platform: "Offline",
  },
  {
    id: "28",
    title: "Ruang Aspirasi Mahasiswa",
    date: "June 15, 2025",
    type: "Mimbar Mahasiswa",
    platform: "Offline",
  },
  {
    id: "29",
    title: "Sharing Session #14",
    date: "June 26, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "30",
    title: "Penerimaan Anggota Baru",
    date: "July 7, 2025",
    type: "Penerimaan Anggota Baru",
    platform: "Online",
  },
  {
    id: "31",
    title: "Orientasi Anggota Baru",
    date: "July 14, 2025",
    type: "Orientasi Anggota Baru",
    platform: "Online",
  },
  {
    id: "32",
    title: "Ruang Aspirasi Mahasiswa, Rapat Umum",
    date: "July 20, 2025",
    type: "Mimbar Mahasiswa",
    platform: "Offline",
  },
  {
    id: "33",
    title: "Sharing Session #15",
    date: "August 13, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "34",
    title: "Ruang Aspirasi Mahasiswa",
    date: "August 17, 2025",
    type: "Mimbar Mahasiswa",
    platform: "Offline",
  },
  {
    id: "35",
    title: "Workshop/Diklat",
    date: "August 27, 2025",
    type: "Workshop",
    platform: "Online",
  },
  {
    id: "36",
    title: "Sharing Session #16",
    date: "September 3, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "37",
    title: "Ruang Aspirasi Mahasiswa, Rapat Umum",
    date: "September 21, 2025",
    type: "Mimbar Mahasiswa",
    platform: "Offline",
  },
  {
    id: "38",
    title: "Sharing Session #17",
    date: "September 24, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "39",
    title: "Sharing Session #18",
    date: "October 8, 2025",
    type: "Sharing Session",
    platform: "Online",
  },
  {
    id: "40",
    title: "Ruang Aspirasi Mahasiswa",
    date: "October 19, 2025",
    type: "Mimbar Mahasiswa",
    platform: "Online",
  },
  {
    id: "41",
    title: "Mubes Penristek",
    date: "October 26, 2025",
    type: "Mubes",
    platform: "Offline",
  },
  {
    id: "42",
    title: "Tata Cara Bersidang",
    date: "October 29, 2025",
    type: "TCB",
    platform: "Offline",
  },
];
